apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-hello-v2
  labels:
    app: dj-hello-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj-hello-v2
  template:
    metadata:
      labels:
        app: dj-hello-v2
        service: dj-hello
        version: v2
    spec:
      containers:
        - name: dj-hello-v2
          image: amjedsaleel/dj-hello:v2.1
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db-password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: db-port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-dj
                  key: postgres_db_url