apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "t5.amjedsaleel.tech"
  gateways:
  - sample-gateway
  http:
    - route:
      - destination:
          host: version1 # service name
          # subset: v1
        weight: 50
      - destination:
          host: version2.default.svc.cluster.local # service name
          # subset: v2
        weight: 50